### ISSUE TITLE
Wild-card selector does not work

### ISSUE THREAD

**Issue by alansouzati** [mbasso/styled-components-test-utils#11]
**General Information**

- [x] Bug
- [ ] Improvement
- [ ] Feature
- [ ] Other

**Description**

`expect({ component, modifier: "& *:not([fill='none'])" }).toHaveStyleRule('fill', '#767676');`

Notice that there is a wild-card selector and other regex-valid syntax. I think we need to escape the `modifier` string before creating a regular expression for it.

**Steps to reproduce**

(Add link to a demo on https://jsfiddle.net or similar if possible)
1. Add a style that has a wild-card selector or other regex-valid character
2. Notice that the test never passes since the regex is not picking up the right style object (regex match returns null)

**Versions**

- styled-components-test-utils: latest
- node: 8.12.0
- chai: latest

**Comment by alansouzati** [comment]
I'm sending a PR to fix this.

**Comment by mbasso** [comment]
Hi @alansouzati,
thank you for opening this issue and following through with a PR, I really appreciate it 😄
Awesome, looks good to me, I'll merge and publish a release as soon as possible!

**Comment by mbasso** [comment]
Just published [styled-components-test-utils@0.5.0](https://github.com/mbasso/styled-components-test-utils/releases/tag/0.5.0) with this fix, thank you 🎉
