### ISSUE TITLE
Multiple media queries fail to assert

### ISSUE THREAD

**Issue by alansouzati** [mbasso/styled-components-test-utils#14]
**General Information**

- [x] Bug
- [ ] Improvement
- [ ] Feature
- [ ] Other

**Description**

(Add images if possible)

```
expect({
      component,
      media: 'screen and (max-width:3840px) and (min-width:600px)',
    })
```
This should work and it fails
**Steps to reproduce**

(Add link to a demo on https://jsfiddle.net or similar if possible)

**Versions**

- styled-components-test-utils: lastest
- node: 10

**Comment by mbasso** [comment]
Awesome! Thank you so much for the effort and time you are putting in this library 😄 

I'll merge and publish a new release soon

**Comment by mbasso** [comment]
@alansouzati [styled-components-test-utils@1.0.0](https://github.com/mbasso/styled-components-test-utils/releases/tag/1.0.0) is now online 🎉
