### ISSUE TITLE
Multiple media query with the same boundaries breaks test

### ISSUE THREAD

**Issue by alansouzati** [mbasso/styled-components-test-utils#17]
**General Information**

- [x] Bug
- [ ] Improvement
- [ ] Feature
- [ ] Other

**Description**

this should work, as it is a valid css construct

```
@media screen and (max-width: 600px) {
    &:hover {
      color: purple;
    }
  }

  @media screen and (max-width: 600px) {
    &:active {
      color: red;
    }
  }
```
but the test fails it is does not extract all media queries code.

**Steps to reproduce**

(Add link to a demo on https://jsfiddle.net or similar if possible)

**Versions**

- styled-components-test-utils: 1.0.0
- node: latest

**Comment by mbasso** [comment]
styled-components-test-utils@1.0.1 is now online 🎉 
thank you!
