### ISSUE TITLE
I this React 16 / Enzyme 3 compliant?

### ISSUE THREAD

**Issue by joetidee** [mbasso/styled-components-test-utils#3]
Have introduced this library into my tests and am now getting the message:

> 
> Attempted to access ReactWrapper::node, which was previously a private property on
>             Enzyme ReactWrapper instances, but is no longer and should not be relied upon.
>             Consider using the getElement() method instead.

**Comment by mbasso** [comment]
Hi @joetidee,
it seems that there is a problem with enzyme 3, I'll check this out in the next few days, as soon as possible

**Comment by joetidee** [comment]
much appreciated :)

**Comment by mbasso** [comment]
Fixed in version [0.3.1](https://github.com/mbasso/styled-components-test-utils/releases/tag/0.3.1). Thank you for opening this issue 😄
